export const fidgets = [
  {
    id: 'pop',
    name: 'Pop it',
    category: 'Tap',
    color: '#c6f581',
    description: 'A little pop. A lot of satisfaction.',
    instruction: 'Tap the bubbles. Find your rhythm.',
    tag: 'THE CROWD FAVORITE',
  },
  {
    id: 'switch',
    name: 'Switchboard',
    category: 'Tap',
    color: '#d7b5ff',
    description: 'Absolutely nothing to turn on. Everything to switch.',
    instruction: 'Flip a switch. Or all of them.',
    tag: 'CLICK INTO CALM',
  },
  {
    id: 'dial',
    name: 'Click wheel',
    category: 'Slide',
    color: '#a7cfff',
    description: 'One more turn. Just one more.',
    instruction: 'Drag around the wheel to feel every notch.',
    tag: 'PERFECTLY POINTLESS',
  },
  {
    id: 'marble',
    name: 'Gravity',
    category: 'Motion',
    color: '#f0c67d',
    description: 'A tiny world that moves with you.',
    instruction: 'Tilt your phone or drag to roll the marble.',
    tag: 'GO WITH THE FLOW',
  },
  {
    id: 'keys',
    name: 'Key crush',
    category: 'Tap',
    color: '#ffc6a5',
    description: 'All the good keys. None of the emails.',
    instruction: 'Tap the keys. Make a little music.',
    tag: 'YOUR KIND OF KEYBOARD',
  },
  {
    id: 'ripple',
    name: 'Still water',
    category: 'Chill',
    color: '#8bd9de',
    description: 'Leave a ripple. Let it go.',
    instruction: 'Touch the water and watch it unfold.',
    tag: 'A MOMENT OF STILL',
  },
  {
    id: 'spinner',
    name: 'Orbit',
    category: 'Slide',
    color: '#b7adff',
    description: 'Less thinking. More spinning.',
    instruction: 'Drag around the center to snap between stops.',
    tag: 'JUST ONE MORE SPIN',
  },
  {
    id: 'zip',
    name: 'Zip it',
    category: 'Slide',
    color: '#f6a6b9',
    description: 'That perfect zzzip, on repeat.',
    instruction: 'Drag the zipper. One tooth, one click.',
    tag: 'UNZIP YOUR MIND',
  },
  {
    id: 'bubble',
    name: 'Bubble wrap',
    category: 'Tap',
    color: '#a3d8f6',
    description: 'The best part of getting a package.',
    instruction: 'Pop every bubble. Fresh wrap is always ready.',
    tag: 'HANDLE WITH JOY',
  },
  {
    id: 'breath',
    name: 'Soft landing',
    category: 'Chill',
    color: '#b8d1a2',
    description: 'A small pause for a busy mind.',
    instruction: 'Follow the circle. Breathe at your own pace.',
    tag: 'ROOM TO BREATHE',
  },
  {
    id: 'rain',
    name: 'Rain stick',
    category: 'Motion',
    color: '#f0d78d',
    description: 'A pocketful of falling stars.',
    instruction: 'Shake your phone or tap to scatter the beads.',
    tag: 'SHAKE THE DAY OFF',
  },
  {
    id: 'spring',
    name: 'Squish',
    category: 'Slide',
    color: '#ffac96',
    description: 'A stress ball that always bounces back.',
    instruction: 'Press and drag to stretch. Release to let go.',
    tag: 'LET IT ALL GO',
  },
] as const;
export type FidgetId = (typeof fidgets)[number]['id'];
